name: Trigger auto deployment for copilot-azure-pricing

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/copilot-azure-pricing-AutoDeployTrigger-838804fc-3007-4c14-be2d-045176408cdd.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.COPILOTAZUREPRICING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.COPILOTAZUREPRICING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.COPILOTAZUREPRICING_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: copilotazurepricing.azurecr.io
          registryUsername: ${{ secrets.COPILOTAZUREPRICING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.COPILOTAZUREPRICING_REGISTRY_PASSWORD }}
          containerAppName: copilot-azure-pricing
          resourceGroup: copilot-demo
          imageToBuild: copilotazurepricing.azurecr.io/copilot-azure-pricing:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


